
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_name VARCHAR(255) NOT NULL,
    order_date TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL , CHECK (status IN ('PENDING', 'SHIPPED', 'DELIVERED', 'CANCELED')),
    total_amount NUMERIC(12, 2) NOT NULL,
    shipping_address VARCHAR(255) NOT NULL,
    payment_method VARCHAR(255) NOT NULL CHECK (payment_method IN ('CREDIT_CARD', 'PAYPAL', 'CASH')),
    notes TEXT
);
